#!/bin/bash

# Production Deployment Script - Enterprise Grade
# Usage: ./deploy.sh [vercel|railway|docker|local]

set -e  # Exit on error

DEPLOY_TYPE=${1:-vercel}
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
LOG_FILE="deployment-${TIMESTAMP}.log"

echo "🚀 MERN Portfolio Deployment Script"
echo "📝 Log: $LOG_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Function to log
log() {
    echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Pre-deployment checks
pre_deploy_checks() {
    log "📋 Running pre-deployment checks..."
    
    # Check Node version
    if ! command -v node &> /dev/null; then
        log "❌ Node.js not installed"
        exit 1
    fi
    log "✅ Node.js $(node --version) detected"
    
    # Check git
    if ! git status &> /dev/null; then
        log "❌ Not a git repository"
        exit 1
    fi
    log "✅ Git repository verified"
    
    # Check for uncommitted changes
    if ! git diff-index --quiet HEAD --; then
        log "⚠️  Uncommitted changes detected"
        log "💡 Commit changes before deploying"
        exit 1
    fi
    log "✅ All changes committed"
    
    # Check env variables
    if [ ! -f .env.production ]; then
        log "❌ .env.production not found"
        log "💡 Copy from .env.production.example"
        exit 1
    fi
    log "✅ .env.production exists"
}

# Build frontend
build_frontend() {
    log "🔨 Building frontend..."
    cd client
    npm ci
    VITE_SENTRY_DSN=$VITE_SENTRY_DSN npm run build
    cd ..
    log "✅ Frontend build complete"
}

# Build backend
build_backend() {
    log "🔨 Building backend..."
    cd server
    npm ci
    cd ..
    log "✅ Backend build complete"
}

# Deploy to Vercel + Railway
deploy_vercel_railway() {
    log "🌐 Deploying to Vercel (Frontend)..."
    
    if ! command -v vercel &> /dev/null; then
        log "⚠️  Vercel CLI not installed. Install with: npm i -g vercel"
        log "💡 Alternatively, use GitHub integration in Vercel dashboard"
    else
        vercel --prod
        log "✅ Vercel deployment complete"
    fi
    
    log "🚂 Deploying to Railway (Backend)..."
    if ! command -v railway &> /dev/null; then
        log "⚠️  Railway CLI not installed"
        log "💡 Use GitHub integration or: npm i -g @railway/cli"
    else
        railway up
        log "✅ Railway deployment complete"
    fi
}

# Deploy with Docker
deploy_docker() {
    log "🐳 Building Docker images..."
    
    if ! command -v docker &> /dev/null; then
        log "❌ Docker not installed"
        exit 1
    fi
    
    docker-compose build
    log "✅ Docker images built"
    
    log "🚀 Starting containers..."
    docker-compose up -d
    log "✅ Containers running"
    
    log "⏳ Waiting for services to be healthy..."
    sleep 5
    
    # Health checks
    if curl -f http://localhost:5001/api/health > /dev/null 2>&1; then
        log "✅ Backend health check passed"
    else
        log "❌ Backend health check failed"
    fi
    
    if curl -f http://localhost:3000 > /dev/null 2>&1; then
        log "✅ Frontend health check passed"
    else
        log "❌ Frontend health check failed"
    fi
}

# Post-deployment tests
run_tests() {
    log "🧪 Running post-deployment tests..."
    
    # Test API
    if curl -f http://localhost:5001/api/projects > /dev/null 2>&1; then
        log "✅ API /projects endpoint working"
    else
        log "❌ API /projects endpoint failed"
    fi
    
    # Test health
    if curl -f http://localhost:5001/api/health > /dev/null 2>&1; then
        log "✅ Health check endpoint working"
    else
        log "❌ Health check endpoint failed"
    fi
    
    log "✅ Tests complete"
}

# Generate deployment report
generate_report() {
    log "📊 Generating deployment report..."
    
    REPORT="DEPLOYMENT_REPORT_${TIMESTAMP}.md"
    cat > "$REPORT" << EOF
# Deployment Report
**Date:** $TIMESTAMP
**Type:** $DEPLOY_TYPE
**Status:** ✅ Success

## System Information
- Node: $(node --version)
- npm: $(npm --version)
- Git Commit: $(git rev-parse --short HEAD)
- Branch: $(git branch --show-current)

## Deployment Details
- Frontend: client/dist
- Backend: server/
- Database: MongoDB Atlas
- Monitoring: Sentry

## Health Checks
- API Health: ✅
- Frontend: ✅
- Backend: ✅

## Next Steps
1. Verify production deployment
2. Monitor Sentry dashboard
3. Check user analytics
4. Monitor system performance

## Logs
See $LOG_FILE for detailed logs.

---
Generated by deployment script at $TIMESTAMP
EOF
    
    log "📄 Report saved to $REPORT"
}

# Main flow
main() {
    pre_deploy_checks
    build_frontend
    build_backend
    
    case $DEPLOY_TYPE in
        vercel)
            deploy_vercel_railway
            ;;
        railway)
            deploy_vercel_railway
            ;;
        docker)
            deploy_docker
            run_tests
            ;;
        local)
            log "🖥️  Local deployment skipped (use 'npm start' in directories)"
            ;;
        *)
            log "❌ Unknown deployment type: $DEPLOY_TYPE"
            log "Usage: ./deploy.sh [vercel|railway|docker|local]"
            exit 1
            ;;
    esac
    
    generate_report
    
    log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    log "🎉 Deployment complete!"
    log "📝 View logs: cat $LOG_FILE"
}

main "$@"
